applications:
-   name: platformtest
    vms:
    -   name: centos6
        sysinit: "yum -y install dbus-devel dbus-x11"
    -   name: fedora16
        sysinit: "yum -y install dbus-devel dbus-x11"
    -   name: fedora17
        sysinit: "yum -y install dbus-devel dbus-x11"
    -   name: ubuntu1204
        sysinit: "apt-get update && apt-get install libdbus-1-dev"
